name:                hs-proofs-with-types
version:             0.1.0.0
github:              "githubuser/hs-proofs-with-types"
license:             BSD3
author:              "Author name here"
maintainer:          "mikkelmilo+github@gmail.com"
copyright:           "2019 Mikkel Milo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hs-proofs-with-types#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  hs-proofs-with-types-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-proofs-with-types

tests:
  hs-proofs-with-types-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-proofs-with-types
